name: Build and Deploy Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'web/**'
  pull_request:
    branches:
      - main
    paths:
      - 'web/**'
  workflow_dispatch:

jobs:
  build:
    name: Build Frontend
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: web/package-lock.json
          
      - name: Install dependencies
        working-directory: ./web
        run: npm ci
        
      - name: Build application
        working-directory: ./web
        run: npm run build
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: web/dist/
          retention-days: 7

  # Uncomment this job when ready to deploy to Azure Static Web Apps
  # deploy:
  #   name: Deploy to Azure Static Web Apps
  #   runs-on: ubuntu-latest
  #   needs: build
  #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
  #   
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #       
  #     - name: Download build artifacts
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: frontend-dist
  #         path: web/dist/
  #         
  #     - name: Deploy to Azure Static Web Apps
  #       uses: Azure/static-web-apps-deploy@v1
  #       with:
  #         azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
  #         repo_token: ${{ secrets.GITHUB_TOKEN }}
  #         action: "upload"
  #         app_location: "web/dist"
  #         skip_app_build: true
