---
name: Main Branch CI/CD

'on':
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - 'deploy/**'
      - '.github/workflows/infrastructure-*.yml'

env:
  DOTNET_VERSION: '9.0.x'
  # Set this to your Azure Container Registry name
  # (e.g., 'myregistry.azurecr.io')
  REGISTRY_NAME: ''
  # Set this to your Azure resource group containing the ACR
  AZURE_RESOURCE_GROUP: ''
  # Set this to your Azure subscription ID
  AZURE_SUBSCRIPTION_ID: ''

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and Test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release --no-restore

      - name: Run tests
        run: |
          dotnet test --configuration Release --no-build \
            --verbosity normal --collect:"XPlat Code Coverage" \
            --results-directory ./TestResults \
            --logger "trx;LogFileName=TestResults.trx"

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            TestResults/
            **/TestResults/
          retention-days: 30

  build-and-push-containers:
    runs-on: ubuntu-latest
    name: Build and Push Docker Images
    needs: build-and-test
    if: env.REGISTRY_NAME != ''

    # Grant GITHUB_TOKEN the permissions required to authenticate
    # with Azure via federated identity
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login via OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Azure Container Registry
        run: |
          az acr login --name $(echo ${{ env.REGISTRY_NAME }} | cut -d'.' -f1)

      - name: Extract metadata for MinimalApi
        id: meta-api
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_NAME }}/serverless-benchmark-api
          tags: |
            type=ref,event=branch
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Extract metadata for BenchmarkRunner
        id: meta-runner
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_NAME }}/serverless-benchmark-runner
          tags: |
            type=ref,event=branch
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push MinimalApi Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: src/MinimalApi/Dockerfile
          push: true
          tags: ${{ steps.meta-api.outputs.tags }}
          labels: ${{ steps.meta-api.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push BenchmarkRunner Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: src/BenchmarkRunner/Dockerfile
          push: true
          tags: ${{ steps.meta-runner.outputs.tags }}
          labels: ${{ steps.meta-runner.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-containers-dry-run:
    runs-on: ubuntu-latest
    name: Build Docker Images (Dry Run)
    needs: build-and-test
    if: env.REGISTRY_NAME == ''

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build MinimalApi Docker image (no push)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: src/MinimalApi/Dockerfile
          push: false
          tags: serverless-benchmark-api:latest
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build BenchmarkRunner Docker image (no push)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: src/BenchmarkRunner/Dockerfile
          push: false
          tags: serverless-benchmark-runner:latest
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Registry Configuration Notice
        run: |
          echo "::notice title=Registry Configuration::To enable container \
          registry push, configure the following: 1) Set REGISTRY_NAME, \
          AZURE_RESOURCE_GROUP, and AZURE_SUBSCRIPTION_ID environment \
          variables, 2) Set up Azure federated identity with AZURE_CLIENT_ID \
          and AZURE_TENANT_ID secrets, 3) Grant the service principal \
          AcrPush role on your container registry"
